### ISSUE TITLE
Realm 사용 방식 개선

### ISSUE THREAD

**Issue by minsoopark** [imtherealk/todolist#6]
Realm을 사용할 때,

UI단 코드에서 Realm에 직접 접근하여 데이터를 가져오는 방식 보다는 

Realm에서 필요한 데이터를 가져오는 메소드를 담는 하나의 커다란 Wrapper 클래스를 만들어 사용하는 것이 좋아보이네요.

예를 들어 해당 Wrapper 클래스를 Foo라고 한다면 

```
Foo foo = Foo.getInstance();
List<Todo> todos = foo.getAllTodos();
```

이런 형태로 데이터를 가져올수 있도록요.

궁극적으로는 UI를 다루는 프론트엔드 코드와 데이터를 다루는 백엔드 코드를 최대한 분리시키기 위함입니다.

**Comment by ghost** [comment]
ㅎㅎ감사함니당 지금은 일단 Realm 쓰는 거부터 하나씩 해보고 큰 거 만들 때 참고할게요!
